hmrc/paye-registration-frontend

- app/controllers/userJourney/WelcomeController.scala
- app/views/govuk_wrapper.scala.html
- app/views/helpers/phaseBanner.scala.html
- app/views/pages/welcome.scala.html
- conf/app.routes
- test/controllers/userJourney/WelcomeControllerSpec.scala
Cleaning up code - Alpha banner is now in the right place and clicking continue in the welcome page no longer adds the user's csrf token into a GET request
> Scrs 3842 summary model

- app/connectors/PAYERegistrationConnector.scala
- app/forms/test/TestPAYERegSetupForm.scala
- app/models/BusinessContactDetails.scala
- app/models/api/PAYERegistration.scala
- app/services/PAYERegistrationService.scala
- app/views/pages/test/payeRegistrationSetup.scala.html
- conf/messages
- test/connectors/PAYERegistrationConnectorSpec.scala
- test/fixtures/PAYERegistrationFixture.scala
- test/services/PAYERegistrationServiceSpec.scala
- test/views/pages/SummarySpec.scala
**Merge after** BCD view and connectors
> SCRS-4506: STEP 3 -  Summary updated for business contact details

- app/connectors/PAYERegistrationConnector.scala
- app/controllers/userJourney/CompanyDetailsController.scala
- app/forms/test/TestPAYERegCompanyDetailsSetupForm.scala
- app/forms/test/TestPAYERegSetupForm.scala
- app/models/api/CompanyDetails.scala
- app/models/api/PAYERegistration.scala
- app/models/view/CompanyDetails.scala
- app/services/CompanyDetailsService.scala
- app/services/PAYERegistrationService.scala
- it/payeregistrationapi/PayeRegistrationConnectorISpec.scala
- test/connectors/PAYERegistrationConnectorSpec.scala
- test/controllers/userJourney/CompanyDetailsControllerSpec.scala
- test/fixtures/PAYERegistrationFixture.scala
- test/fixtures/S4LFixture.scala
- test/services/CompanyDetailsServiceSpec.scala
- test/services/PAYERegistrationServiceSpec.scala
> update company details view model + service

- app/connectors/PAYERegistrationConnector.scala
- app/controllers/userJourney/EligibilityController.scala
- app/controllers/userJourney/SignInOutController.scala
- app/controllers/userJourney/WelcomeController.scala
- app/forms/eligibility/CompanyEligibilityForm.scala
- app/forms/eligibility/DirectorEligibilityForm.scala
- app/models/api/Eligibility.scala
- app/models/view/Eligibility.scala
- app/services/EligibilityService.scala
- app/services/NatureOfBusinessService.scala
- app/views/pages/eligibility/companyEligibility.scala.html
- app/views/pages/eligibility/directorEligibility.scala.html
- app/views/pages/eligibility/ineligible.scala.html
- conf/app.routes
- conf/messages
- it/frontend/EligiblityMethodISpec.scala
- test/connectors/PAYERegistrationConnectorSpec.scala
- test/controllers/userJourney/EligibilityControllerSpec.scala
- test/controllers/userJourney/SignInOutControllerSpec.scala
- test/controllers/userJourney/WelcomeControllerSpec.scala
- test/services/EligibilityServiceSpec.scala
- test/services/EmploymentServiceSpec.scala
I tried to write an integration test to prove the hand off to Comp Reg FE but I hit a bit of a wall... either help or a backlog task is required
> Added Eligibility block

- app/connectors/CompanyRegistrationConnector.scala
- app/controllers/test/FeatureSwitchController.scala
- app/utils/FeatureManager.scala
- conf/application.conf
- conf/test.routes
- it/frontend/DirectorDetailsMethodISpec.scala
- it/payeregistrationapi/CompanyRegistrationConnectorISpec.scala
- it/service/CurrentProfileServiceISpec.scala
- test/connectors/CompanyRegistrationConnectorSpec.scala
- test/controllers/test/FeatureSwitchControllerSpec.scala
Requires App config merge:
https://github.tools.tax.service.gov.uk/HMRC/app-config-base/pull/595
> Added feature switch so we can fetch details from CR

- app/common/exceptions/DownstreamExceptions.scala
- app/connectors/IncorporationInformationConnector.scala
- app/forms/directorDetails/DirectorDetailsForm.scala
- app/services/DirectorDetailsService.scala
- app/services/IncorporationInformationService.scala
- app/services/MetricsService.scala
- it/payeregistrationapi/IncorporationInformationConnectorISpec.scala
- test/connectors/IncorporationInformationConnectorSpec.scala
- test/forms/directorDetails/DirectorDetailsFormSpec.scala
- test/mocks/MockMetrics.scala
- test/services/CoHoAPIServiceSpec.scala
- test/services/DirectorDetailsServiceSpec.scala
Also need review PR for grafana-dashboards
https://github.tools.tax.service.gov.uk/HMRC/grafana-dashboards/pull/573
> refactor coHoAPI to incorpInfo + fix empty officer list

- app/utils/SessionProfile.scala
- conf/app.routes
- it/frontend/CompanyDetailsMethodISpec.scala
- it/frontend/EligiblityMethodISpec.scala
- it/frontend/RestartPAYEISpec.scala
- test/controllers/userJourney/CompanyDetailsControllerSpec.scala
- test/controllers/userJourney/DirectorDetailsControllerSpec.scala
- test/controllers/userJourney/EligibilityControllerSpec.scala
- test/controllers/userJourney/EmploymentControllerSpec.scala
- test/controllers/userJourney/PAYEContactControllerSpec.scala
- test/controllers/userJourney/PayeStartControllerSpec.scala
- test/controllers/userJourney/SummaryControllerSpec.scala
- test/utils/SessionProfileSpec.scala
**Requires ATs and PTs first**
> Updated URLs to new content design

- app/audit/PPOBAddressAuditEventDetail.scala
- app/audit/RegistrationAuditEvent.scala
- app/controllers/userJourney/DirectorDetailsController.scala
- app/models/api/Directors.scala
- app/models/view/Directors.scala
- app/services/DirectorDetailsService.scala
- app/services/IncorporationInformationService.scala
- app/views/helpers/templates/inputRadioGroupHidden.scala.html
- app/views/helpers/templates/payeInputRadioGroup.scala.html
- app/views/pages/directorDetails.scala.html
- conf/application.conf
- conf/messages
- it/frontend/DirectorDetailsMethodISpec.scala
- project/FrontendBuild.scala
- test/controllers/userJourney/CompanyDetailsControllerSpec.scala
- test/services/DirectorDetailsServiceSpec.scala
- test/views/pages/DirectorDetailsViewSpec.scala
This version bump uplifts radio buttons to latest version
http://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons
Changes in this PR:
• bump play-ui to 7.5.0 and HMRC AF to 2.248.0
• update local radio button helper with new markup required for new radio buttons
> Bump play-ui to 7.5.0 and HMRC AF to 2.248.1 update radio buttons helper

- app/connectors/AddressLookupConnector.scala
- app/models/Address.scala
- app/models/api/Directors.scala
- app/utils/Formatters.scala
- it/payeregistrationapi/IncorporationInformationConnectorISpec.scala
- test/models/AddressSpec.scala
- test/models/external/CoHoCompanyDetailsSpec.scala
- test/utils/FormattersSpec.scala
> format Officer title, first, middle and last names from II

- app/views/pages/confirmation.scala.html
- app/views/pages/natureOfBusiness.scala.html
- conf/application.conf
- public/stylesheets/paye.css
**New feature**
Assets uplift to 3.3.2
Custom class for grey shading on confirmation page
> SCRS-11068 Assets uplift and confirmation page change

- conf/application.conf
- public/stylesheets/paye.css
**Bug fix**
Revert ASSETS_FRONTEND version + fix CSS on Confirmation page
> [SCRS-11068] revert ASSETS_FRONTEND uplift as it breaks timeout-dialog, fix CSS confirmation page

- conf/application.conf
> minor amendments for app config base bounce for SCRS-12049

- app/forms/employmentDetails/PaidEmployeesForm.scala
- conf/messages
- project/AppDependencies.scala
- test/forms/employmentDetails/PaidEmployeesFormSpec.scala
SCRS-11723 update date validation on employ-anyone page
New feature
> SCRS-11723 update date validation on employ-anyone page

- app/models/view/PAYEContactDetails.scala
- it/frontend/PAYEContactDetailsMethodISpec.scala
- project/AppDependencies.scala
- test/models/PAYEContactDetailsSpec.scala
This is the first deployment of the 4
> SCRS-11997 uplift dep, made prepop contact name optional instead of returning jserror and failing silently

- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
> SCRS-11994 build updates and refactor of build.sbt and minoruplift

- app/connectors/PAYERegistrationConnector.scala
- app/controllers/internal/RegistrationController.scala
- app/enums/RegistrationDeletion.scala
- app/services/PAYERegistrationService.scala
- it/internal/RegistrationMethodISpec.scala
- project/AppDependencies.scala
- test/connectors/PAYERegistrationConnectorSpec.scala
- test/controllers/internal/RegistrationControllerSpec.scala
> SCRS-11902 and dep ulift, added new enum and return 200 to ii if doc not found

- app/views/govuk_wrapper.scala.html
- app/views/pages/companyDetails/tradingName.scala.html
- app/views/pages/confirmation.scala.html
- conf/application.conf
- project/AppDependencies.scala
- public/stylesheets/timeout-dialog1.css
SCRS-12001 Upgrade to assets to 3.7.0 and uplift dependencies## Checklist
> SCRS-12001 Upgrade to assets to 3.7.0 and uplift dependencies

- app/config/Module.scala
- app/config/frontendAppConfig.scala
- app/config/frontendGlobal.scala
- app/config/frontendWiring.scala
- conf/application.conf
- it/internal/RegistrationMethodISpec.scala
removed whitelisting - never used, causing problems in prod
> removed whitelisting due to never being used

- app/controllers/userJourney/EmploymentController.scala
- app/views/pages/employmentDetails/employsSubcontractors.scala.html
- conf/messages
- test/controllers/userJourney/EmploymentControllerSpec.scala
SCRS-12884 - Updates for new tax year
* [X ] I've executed the acceptance test pack locally to ensure there are no regressions
* [X ] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message
* [ X I've run a dependency check to ensure all dependencies are up to date
> SCRS-12884 - Updates for new tax year

- app/controllers/userJourney/EmploymentController.scala
- app/services/ThresholdService.scala
- app/utils/SystemDate.scala
- test/controllers/userJourney/EmploymentControllerSpec.scala
- test/services/ThresholdServiceSpec.scala
SCRS-12884b - final new tax year changes
> SCRS-12884b - final new tax year changes

- app/config/frontendWiring.scala
- project/AppDependencies.scala
- test/forms/employmentDetails/PaidEmployeesFormSpec.scala
SCRS-12888 Dependency uplift for kibana problem
> SCRS-12888 Dependency uplift for kibana problem

- app/utils/NewTaxYear.scala
- conf/messages
SCRS-12912 change to content for Registrations Backlog
> SCRS-12912 change to content for Registrations Backlog

- app/utils/NewTaxYear.scala
- conf/messages
SAR-3835 Update contact date to 26th July
> SAR-3835 Update contact date to 26th July

- project/AppDependencies.scala
- project/plugins.sbt
>  SAR-4132: paye-registration-frontend

- app/utils/NewTaxYear.scala
- conf/messages
- project/AppDependencies.scala
SAR-4208 content change to confirmation page
> SAR-4208 content change to confirmation page

- conf/application.conf
> SAR-4358: SSLEngine exception fix

- app/utils/NewTaxYear.scala
- conf/messages
> SAR-4371 - Updated content of confirmation page

- app/views/pages/confirmation.scala.html
- conf/messages
SAR-4979 - Update to content on Confirmation screen
> SAR-4979 - Update to content on Confirmation screen

- app/views/pages/confirmation.scala.html
- conf/messages
> SAR-5127 - Update to confirmation page content

- README.md
- app/config/frontendAppConfig.scala
- app/views/timeout_script.scala.html
- conf/application.conf
- public/javascripts/timeout-dialog.js
> SAR-5380: Fixed timeout dialog focus issue and updated README

- app/controllers/userJourney/EmploymentController.scala
- app/services/ThresholdService.scala
- test/controllers/userJourney/EmploymentControllerSpec.scala
- test/services/ThresholdServiceSpec.scala
> SAR-5410 - update to PAYE thresholds for 6 Apr 2020

- it/frontend/EmploymentISpec.scala
- test/controllers/userJourney/EmploymentControllerSpec.scala
- test/forms/employmentDetails/PaidEmployeesFormSpec.scala
> SAR-5455 Fix to failing tests because we have entered a new tax year

- app/controllers/test/FeatureSwitchController.scala
- app/services/AddressLookupService.scala
- app/utils/FeatureManager.scala
- test/controllers/test/FeatureSwitchControllerSpec.scala
- test/services/AddressLookupServiceSpec.scala
- test/utils/FeatureSwitchSpec.scala
> SAR-5449 removed the ALF feature switch

- app/config/frontendAppConfig.scala
- conf/application.conf
> SAR-5575: Updated appConfig to load contact frontend from config

- app/controllers/userJourney/CompanyDetailsController.scala
- app/views/pages/companyDetails/businessContactDetails.scala.html
- conf/messages
- it/frontend/CompanyDetailsMethodISpec.scala
- test/controllers/userJourney/CompanyDetailsControllerSpec.scala
- test/views/pages/companyDetails/BusinessContactDetailsSpec.scala
SAR-5538 Changed Business contact details page. Changed validation messages and added company name to the page.
> SAR-5538 Changed Business contact details page, validation and added company name

- app/views/pages/companyDetails/businessContactDetails.scala.html
SAR-5577 Added company name to the legend in business contact details
> SAR-5577 Added company name to the legend in business contact details

- app/connectors/AddressLookupConnector.scala
- app/models/external/AlfJourneyConfig.scala
- app/services/AddressLookupConfigBuilderService.scala
- it/frontend/CompanyDetailsControllerISpec.scala
- it/frontend/PAYEContactControllerISpec.scala
- it/itutil/IntegrationSpecBase.scala
- it/itutil/RequestsFinder.scala
- it/itutil/WiremockHelper.scala
- test/services/AddressLookupConfigBuilderServiceSpec.scala
SAR-5587 Moving paye-registration-fe to ALF v2
> SAR-5587 Moving paye-registration-fe to ALF v2

- app/utils/NewTaxYear.scala
- conf/messages
> SAR-5763 - Update to dates on Application Complete screen

- project/AppDependencies.scala
> SAR-5737 - Remove deprecated hmrctest

- app/utils/NewTaxYear.scala
- conf/messages
> SAR-5797 - Reapply summary page date change to 31st August

- app/config/AppConfig.scala
- app/models/external/AlfJourneyConfig.scala
- app/services/AddressLookupConfigBuilderService.scala
- it/frontend/CompanyDetailsControllerISpec.scala
- it/frontend/PAYEContactControllerISpec.scala
- test/services/AddressLookupConfigBuilderServiceSpec.scala
> SAR-5630 Add Accessibility Statement to ALF pages

- app/services/AddressLookupConfigBuilderService.scala
- it/frontend/CompanyDetailsControllerISpec.scala
- it/frontend/PAYEContactControllerISpec.scala
- test/services/AddressLookupConfigBuilderServiceSpec.scala
> SAR-5931: Update page titles to match H1

- app/views/helpers/TitleHelper.scala
- app/views/main_template.scala.html
- app/views/pages/companyDetails/businessContactDetails.scala.html
- app/views/pages/companyDetails/ppobAddress.scala.html
- app/views/pages/companyDetails/tradingName.scala.html
- app/views/pages/completionCapacity.scala.html
- app/views/pages/directorDetails.scala.html
- app/views/pages/employmentDetails/constructionIndustry.scala.html
- app/views/pages/employmentDetails/employsSubcontractors.scala.html
- app/views/pages/employmentDetails/paidEmployees.scala.html
- app/views/pages/employmentDetails/paysPension.scala.html
- app/views/pages/employmentDetails/willBePaying.scala.html
- app/views/pages/natureOfBusiness.scala.html
- app/views/pages/payeContact/correspondenceAddress.scala.html
- app/views/pages/payeContact/payeContactDetails.scala.html
- conf/messages
> SAR-5938: Prefix error: to title when form has errors

- app/views/helpers/TitleHelper.scala
> SAR-5974: Adding space after Error: prefix in title

- app/utils/NewTaxYear.scala
> SAR-6001 - Switch PAYE to use current tax year email and summary page

- app/views/main_template.scala.html
- conf/messages
- it/filters/PAYESessionIDFilterISpec.scala
- it/frontend/CompanyDetailsMethodISpec.scala
- it/frontend/DirectorDetailsMethodISpec.scala
- it/frontend/PAYEContactDetailsMethodISpec.scala
- test/views/statements/AccessibilityStatementViewSpec.scala
> SAR-6006 adding service name to page title

- app/views/helpers/templates/formHiddenYesNoRadio.scala.html
- app/views/helpers/templates/inputRadioGroupHidden.scala.html
- app/views/helpers/templates/payeInputRadioGroup.scala.html
- app/views/pages/companyDetails/ppobAddress.scala.html
- app/views/pages/companyDetails/tradingName.scala.html
- app/views/pages/completionCapacity.scala.html
- app/views/pages/employmentDetails/constructionIndustry.scala.html
- app/views/pages/employmentDetails/employsSubcontractors.scala.html
- app/views/pages/employmentDetails/paidEmployees.scala.html
- app/views/pages/employmentDetails/paysPension.scala.html
- app/views/pages/employmentDetails/willBePaying.scala.html
- app/views/pages/payeContact/correspondenceAddress.scala.html
> SAR-6007 Add H1 within fieldset legend option to all radio helpers

- app/views/pages/employmentDetails/paysPension.scala.html
> SAR-6313 - Fix to missing content on pension payments page

- app/config/AppConfig.scala
- app/connectors/IncorporationInformationConnector.scala
- app/filters/PAYECSRFExceptionsFilter.scala
- app/services/CompanyDetailsService.scala
- app/services/CurrentProfileService.scala
- app/services/DirectorDetailsService.scala
- app/services/SubmissionService.scala
- app/utils/RegistrationAllowlist.scala
- conf/application.conf
- it/frontend/CompanyDetailsControllerISpec.scala
- it/frontend/CompanyDetailsMethodISpec.scala
- it/frontend/DirectorDetailsMethodISpec.scala
- it/frontend/PAYEContactControllerISpec.scala
- it/payeregistrationapi/IncorporationInformationConnectorISpec.scala
- it/services/CurrentProfileServiceISpec.scala
- it/services/SubmissionServiceISpec.scala
- it/utils/SessionProfileISpec.scala
- project/AppDependencies.scala
- test/audit/RegistrationAuditEventSpec.scala
> SAR-6701: Update to use allow list terminology

- it/frontend/CompanyDetailsMethodISpec.scala
- it/itutil/LoginStub.scala
- project/AppDependencies.scala
- test/helpers/auth/SessionBuilder.scala
> SAR-6707 - Remove SessionKeys

- conf/application.conf
> SAR-6737: Remove CA_Frontend

- conf/application.conf
- conf/messages
> SAR-7033: Updated Next Tax Year content

- app/config/AppConfig.scala
- app/views/govuk_wrapper.scala.html
- app/views/helpers/templates/linkNewWindow.scala.html
- app/views/helpers/templates/payeErrorSummary.scala.html
- conf/application.conf
- public/javascripts/paye.js
Removed GA code from Paye Reg FE
> removed GA code

- app/utils/NewTaxYear.scala
- conf/messages
> SAR-7609 - update contact date to 31 August

- app/views/statements/accessibility_statement.scala.html
- conf/messages
- test/views/statements/AccessibilityStatementViewSpec.scala
> SAR-8783 Update accessibility statement

- app/connectors/IncorporationInformationConnector.scala
- app/models/external/OfficerList.scala
- app/services/IncorporationInformationService.scala
- it/payeregistrationapi/IncorporationInformationConnectorISpec.scala
- test/connectors/IncorporationInformationConnectorSpec.scala
- test/helpers/fixtures/CoHoAPIFixture.scala
- test/models/external/OfficerListSpec.scala
> SAR-9022 Ignore Officer when no name_elements

- app/controllers/userJourney/ConfirmationController.scala
- app/views/pages/confirmation.scala.html
- conf/messages
- test/controllers/userJourney/ConfirmationControllerSpec.scala
> SAR-9554 - Update confirmation page to use config driven end date

- app/services/EmailService.scala
> SAR-9570 - Fix to when new tax year email gets sent

- app/controllers/PayeBaseController.scala
- app/controllers/userJourney/ConfirmationController.scala
- app/services/EmailService.scala
- it/frontend/PageVisibilityISpec.scala
- it/itutil/LoginStub.scala
- test/controllers/userJourney/ConfirmationControllerSpec.scala
- test/helpers/PayeComponentSpec.scala
- test/helpers/auth/AuthHelpers.scala
- test/services/EmailServiceSpec.scala
> SAR-9564 - connect to new email templates

- app/controllers/userJourney/ConfirmationController.scala
- app/services/EmailService.scala
- test/controllers/userJourney/ConfirmationControllerSpec.scala
> SAR-9705 - Fix to date format for email and conf screen

- app/config/AppConfig.scala
- app/views/pages/confirmation.scala.html
- test/views/pages/ConfirmationViewSpec.scala
> SAR-9886: Fixing questionnaire link

- app/config/AppConfig.scala
> SAR-9886: Url change

- conf/messages.cy
> SAR-10001: Welsh content fix

- app/connectors/KeystoreConnector.scala
- app/models/DatedSessionMap.scala
- app/repositories/SessionRepository.scala
- conf/application.conf
- it/itutil/CachingStub.scala
- it/repositories/SessionRepositoryISpec.scala
- test/connectors/KeystoreConnectorSpec.scala
- test/helpers/MockedComponents.scala
- test/helpers/PayeComponentSpec.scala
Set to `false` by default locally. Once merged, I'll raise app-config-prs for QA and Staging so that we can re-deploy and check it in the environments. Then we can do Production once we're happy with it.
> [SAR-10381] Add ability to replaceIndexes on startup via application.conf boolean

- app/forms/test/TestPAYERegSetupForm.scala
- app/models/api/Directors.scala
- app/services/DirectorDetailsService.scala
- app/services/IncorporationInformationService.scala
- app/services/SummaryService.scala
- it/payeregistrationapi/IncorporationInformationConnectorISpec.scala
- it/payeregistrationapi/PayeRegistrationConnectorISpec.scala
- test/connectors/IncorporationInformationConnectorSpec.scala
- test/controllers/userJourney/DirectorDetailsControllerSpec.scala
- test/controllers/userJourney/SummaryControllerSpec.scala
- test/forms/test/TestPAYERegSetupFormSpec.scala
- test/helpers/fixtures/CoHoAPIFixture.scala
- test/helpers/fixtures/PAYERegistrationFixture.scala
- test/helpers/fixtures/S4LFixture.scala
- test/models/api/DirectorsSpec.scala
- test/models/external/OfficerListSpec.scala
- test/models/view/DirectorsSpec.scala
- test/services/DirectorDetailsServiceSpec.scala
- test/services/SummaryServiceSpec.scala
https://github.com/hmrc/incorporation-frontend-stubs/pull/33
> Filter out results without a surname

- conf/application.conf
https://github.com/hmrc/app-config-base/pull/7716
https://github.com/hmrc/app-config-production/pull/16171
> SAR-6134 Remove CSRF Bypass

- app/views/pages/completionCapacity.scala.html
- app/views/pages/natureOfBusiness.scala.html
- run.sh
Requires AT change here:
- https://github.com/hmrc/paye-registration-acceptance-tests/pull/42
> [SAR-10695] Remove duplicateId and remove whitespace from 'company secretary' ID

- app/connectors/AddressLookupConnector.scala
- app/connectors/httpParsers/AddressLookupHttpParsers.scala
- app/services/EmploymentService.scala
- it/connectors/AddressLookupConnectorISpec.scala
- test/connectors/httpParsers/AddressLookupHttpParsersSpec.scala
- test/utils/LogCapturingHelper.scala
**Note:**
- #463 should be reviewed and merged prior to this, as this PR is a follow on.
- this is the first of many. Will move on to the other 5 connectors today.
> [SAR-10431c] Refactor AddressLookupConnector introducing custom HTTP Reads

- app/connectors/AddressLookupConnector.scala
- app/connectors/BusinessRegistrationConnector.scala
- app/connectors/httpParsers/AddressLookupHttpParsers.scala
- app/connectors/httpParsers/BusinessRegistrationHttpParsers.scala
- app/services/EmploymentService.scala
- app/services/MetricsService.scala
- it/connectors/AddressLookupConnectorISpec.scala
- test/connectors/BusinessRegistrationConnectorSpec.scala
- test/connectors/httpParsers/AddressLookupHttpParsersSpec.scala
- test/connectors/httpParsers/BusinessRegistrationHttpParsersSpec.scala
- test/controllers/test/CurrentProfileControllerSpec.scala
- test/controllers/userJourney/PayeStartControllerSpec.scala
- test/helpers/mocks/internal/BusinessRegistrationConnectorMock.scala
- test/services/CurrentProfileServiceSpec.scala
- test/services/PrepopulationServiceSpec.scala
- test/utils/LogCapturingHelper.scala
#464 needs to be reviewed and merged prior to this - as this PR follows on from the previous.
> [SAR-10431d] Refactor BusRegConnector and add BusRegHttpParser

- app/connectors/AddressLookupConnector.scala
- app/connectors/BusinessRegistrationConnector.scala
- app/connectors/CompanyRegistrationConnector.scala
- app/connectors/httpParsers/AddressLookupHttpParsers.scala
- app/connectors/httpParsers/BusinessRegistrationHttpParsers.scala
- app/connectors/httpParsers/CompanyRegistrationHttpParsers.scala
- app/models/external/BusinessRegistration.scala
- app/services/EmploymentService.scala
- app/services/MetricsService.scala
- it/connectors/AddressLookupConnectorISpec.scala
- test/connectors/BusinessRegistrationConnectorSpec.scala
- test/connectors/CompanyRegistrationConnectorSpec.scala
- test/connectors/httpParsers/AddressLookupHttpParsersSpec.scala
- test/connectors/httpParsers/BusinessRegistrationHttpParsersSpec.scala
- test/connectors/httpParsers/CompanyRegistrationHttpParsersSpec.scala
- test/controllers/test/CurrentProfileControllerSpec.scala
- test/controllers/userJourney/PayeStartControllerSpec.scala
- test/helpers/mocks/internal/BusinessRegistrationConnectorMock.scala
- test/services/CurrentProfileServiceSpec.scala
- test/services/PrepopulationServiceSpec.scala
- test/utils/LogCapturingHelper.scala
**Note**:
- #464 & #466 should be reviewed and merged prior to this PR
> [SAR-10431e] Refactor CompRegConnector and add CompRegHttpParser

- app/connectors/AddressLookupConnector.scala
- app/connectors/BusinessRegistrationConnector.scala
- app/connectors/CompanyRegistrationConnector.scala
- app/connectors/EmailConnector.scala
- app/connectors/httpParsers/AddressLookupHttpParsers.scala
- app/connectors/httpParsers/BusinessRegistrationHttpParsers.scala
- app/connectors/httpParsers/CompanyRegistrationHttpParsers.scala
- app/connectors/httpParsers/EmailHttpParsers.scala
- app/models/EmailResponse.scala
- app/models/external/BusinessRegistration.scala
- app/services/EmailService.scala
- app/services/EmploymentService.scala
- app/services/MetricsService.scala
- it/connectors/AddressLookupConnectorISpec.scala
- it/connectors/EmailConnectorISpec.scala
- test/connectors/BusinessRegistrationConnectorSpec.scala
- test/connectors/CompanyRegistrationConnectorSpec.scala
- test/connectors/EmailConnectorSpec.scala
- test/connectors/httpParsers/AddressLookupHttpParsersSpec.scala
- test/connectors/httpParsers/BusinessRegistrationHttpParsersSpec.scala
- test/connectors/httpParsers/CompanyRegistrationHttpParsersSpec.scala
- test/connectors/httpParsers/EmailHttpParsersSpec.scala
- test/controllers/test/CurrentProfileControllerSpec.scala
- test/controllers/userJourney/ConfirmationControllerSpec.scala
- test/controllers/userJourney/PayeStartControllerSpec.scala
- test/helpers/mocks/internal/BusinessRegistrationConnectorMock.scala
- test/services/CurrentProfileServiceSpec.scala
- test/services/EmailServiceSpec.scala
- test/services/PrepopulationServiceSpec.scala
- test/utils/LogCapturingHelper.scala
The following should be reviewed and merged first:
- #464 
- #466
- #467
> [SAR-10431f] Refactor EmailConnector and add EmailHttpParser

- app/controllers/internal/RegistrationController.scala
- app/services/PAYERegistrationService.scala
> [DL-9529] add additional logging to companyIncorporation call

- conf/application.conf
> DL-9523 - 2023 Alternative content update

- app/connectors/PAYERegistrationConnector.scala
- app/connectors/httpParsers/AddressLookupHttpParsers.scala
- app/connectors/httpParsers/BaseHttpReads.scala
- app/connectors/httpParsers/BusinessRegistrationHttpParsers.scala
- app/connectors/httpParsers/CompanyRegistrationHttpParsers.scala
- app/connectors/httpParsers/IncorporationInformationHttpParsers.scala
- app/connectors/httpParsers/PAYERegistrationHttpParsers.scala
- app/services/PAYERegistrationService.scala
- test/connectors/httpParsers/PAYERegistrationHttpParsersSpec.scala
> DL-BugNotFoundFix - changed the reads to allow for not found

- app/common/exceptions/DownstreamExceptions.scala
- app/config/AppConfig.scala
- app/connectors/BusinessRegistrationConnector.scala
- app/connectors/httpParsers/BaseHttpReads.scala
- app/connectors/httpParsers/BusinessRegistrationHttpParsers.scala
- app/connectors/test/TestBusinessRegConnector.scala
- app/controllers/userJourney/PayeStartController.scala
- app/services/CurrentProfileService.scala
- it/connectors/BusinessRegistrationConnectorISpec.scala
- test/connectors/BusinessRegistrationConnectorSpec.scala
- test/connectors/httpParsers/BusinessRegistrationHttpParsersSpec.scala
- test/controllers/userJourney/PayeStartControllerSpec.scala
> [DL-9555] Redirect users to OTRS if they don't have an SCRS footprint

- app/common/exceptions/DownstreamExceptions.scala
- app/connectors/httpParsers/CompanyRegistrationHttpParsers.scala
- app/controllers/userJourney/CompanyDetailsController.scala
- app/controllers/userJourney/PAYEContactController.scala
- app/controllers/userJourney/PayeStartController.scala
- it/connectors/AddressLookupConnectorISpec.scala
- it/connectors/BusinessRegistrationConnectorISpec.scala
- it/connectors/CompanyRegistrationConnectorISpec.scala
- it/connectors/IncorporationInformationConnectorISpec.scala
- test/connectors/IncorporationInformationConnectorSpec.scala
- test/connectors/httpParsers/AddressLookupHttpParsersSpec.scala
- test/connectors/httpParsers/BusinessRegistrationHttpParsersSpec.scala
- test/connectors/httpParsers/CompanyRegistrationHttpParsersSpec.scala
- test/connectors/httpParsers/IncorporationInformationHttpParsersSpec.scala
- test/connectors/httpParsers/PAYERegistrationHttpParsersSpec.scala
- test/services/PrepopulationServiceSpec.scala
> DL-9843 - Refactored DownStreamException

- app/models/api/Directors.scala
- app/utils/Formatters.scala
- test/utils/FormattersSpec.scala
> DL-10868 - Update Director Title converter to match API doc

- app/config/AppConfig.scala
- app/services/ThresholdService.scala
- app/utils/TaxYearConfig.scala
- app/views/pages/confirmation.scala.html
- app/views/pages/employmentDetails/willBePaying.scala.html
- conf/application.conf
- project/plugins.sbt
- test/services/EmailServiceSpec.scala
- test/services/ThresholdServiceSpec.scala
> DL-12758 - removed year from dates and fixed bugs
